@È  ½ VIDWAÎ SHRÉ K® G® SUBRAYÁ SHARMA<R>MÙ BELOVEÄ  ANÄ  BLESSEÄ 
GURÕ 
Iô ió á distincô privilegå anä pleasurå tï saù á fe÷ wordó  abouô 
mù brieæ timå witè thå renowneä scholaò oæ Vedanta¬ Vidwaî  shré 
K® G® Subrayá Sharmá iî Bangalore.
Armeä onlù witè aî intenså desirå tï understanä ``Amanaská Yoga'§ 
aó  expoundeä  bù Gaudapadacharya¬ É haä approacheä  Vidwaî  Shré 
Sharmá  foò helğ iî understandinç seveî verseó forí thå  Mandukyá 
Kariká  bù  Gaudapadacharya® Iô ió indicativå oæ  hió  remarkablå 
kinä-heartednesó  anä dedicatioî tï Vedantá thaô  hå  immediatelù 
agreeä  tï  spenä  aî houò eacè daù witè me¬  á  totaì  stranger¬ 
despitå hió extremelù busù dailù schedulå oæ teachinç Vedantá alì 
oveò  Bangalore® Despitå mù obviouó deficiencieó iî knowledgå  oæ 
Sanskriô anä pooò traininç iî Vedanta¬ hå taughô må patientlù foò 
siø weekó anä showereä må witè affectionatå attention.
Aó á teacheò Vidwaî Shré Sharmá ió awesome® Havinç spenô 1¶ yearó 
aó  á youtè servinç hió Guru¬ Swamé Satchidanandendrá  Saraswathé 
oæ Holenarasipur¬ hå haó devoteä hió lifå tï spreadinç thå wisdoí 
oæ Vedanta® Hió masterù oæ thå wholå bodù oæ Shankara'ó  writingó 
oî  Vedanta¬ bolstereä bù á masterù oæ Sanskriô anä á varietù  oæ 
ancillarù disciplineó sucè aó Patanjali'ó Yogá Sutras¬ haó  giveî 
Vidwaî   Shré  Sharmá  á  uniquå  capacitù  tï   dispeì   populaò 
misunderstandingó  oæ  Vedantiã  concepts®  Hå  ió  tirelesó   iî 
conveyinç tï studentó thå profounä insightó hå haó gaineä froí  á 
lifå-lonç devotioî tï Vedanta® Hå ió alwayó eageò tï expounä  thå 
deepesô leveì oæ meaninç iî thå mosô simplå anä practicaì wayó tï 
helğ  thå  student¬  understanä  Vedanta<197>eveî  thå  extremelù 
subtlå  ideaó  containeä  iî  workó  sucè  aó   Gaudapadacharya'ó 
Mandukyá  Kariká  anä  Shankaracharya'ó  Bhashyá  oî  thå  Brahmá 
Sutras.
Exudinç  á  deeğ  reverencå  foò  thå  gurõ  parampará  thaô  haó 
preserveä   anä  transmitteä  thió  noblå  knowledgå   oveò   thå 
millennia¬   Vidwaî  Shré  Sharmá  conveyó  hió  enthusiasí   anä 
infectiouó energù tï hió students® Hió lifå stylå ió  disarminglù 
simplå  anä maintainó á stauncè adherencå tï traditionaì  values® 
Aô  thå  samå time¬ aó á truå Vidantin¬ hå ió perfectlù  aô  easå 
witè peoplå froí alì walkó oæ lifå anä alì corneró oæ thå  world® 
Theså  enviablå qualitieó makå hií aî exemplaò oæ thå abilitù  tï 
applù  Vedantiã principleó iî thå contexô oæ moderî familù  life® 
Thå  sheeò  joù  thaô  hå  himselæ  obviouslù  deriveó  froí  thå Šcontemplatioî oæ Vedantá ió á greaô inspiratioî tï alì thoså  whï 
comå iî contacô witè him.
É aí deeplù gratefuì tï Vidwaî Shré Sharmá anä hió familù foò thå 
overwhelminç  warmtè  anä affectioî witè whicè theù  accepteä  mù 
dailù   intrusionó  intï  theiò  home®  Thankó  tï  hió   patienô 
instruction¬  É havå gaineä immeasurablù iî mù  understandinç  oæ 
Vedanta®  É  hopå  anä  praù thaô É caî finä  wayó  tï  puô  thió 
understandinç  tï  gooä uså iî mù owî life®  Likå  me¬  spirituaì 
seekeró everywherå arå indeeä blesseä tï bå guideä bù aî  eruditå 
scholaò anä dedicateä teacheò sucè aó Vidwaî Shré Sharma.
@SIGÎ ½ Dateº 1-04-2009	Dr® D.C® Rao<R>	Washingtoî D.C®, USA
