ÀÈ ½ Sré Sharmaji'ó Discourseó iî Germany
Wheî  É visiteä Bangalorå É meô Vidwaî K® G® Subrayá Sharmá iî  á 
clasó  wherå  hå  waó teachinç  Bruhadaranyaká  Bhashyaí  oæ  Sré 
Shankaracharya® Afteò thå clasó É requesteä hií iæ hå coulä teacè 
må Rudrá Vedá Mantraó anä Vedantas® Iî spitå oæ hió busù schedulå 
withouô  á biô oæ hesitation¬ hå readilù agreeä tï teach® Anä  hå 
taughô  må somå Vedá Mantraó anä Vedantaó foò nearlù  fouò  weekó 
everydaù aô hió residence.
Oî ouò requesô Vidwaî Sré Sharmajé camå tï Germanù anä spenô timå 
witè   uó  iî  Germanù  froí  2³-0µ-200¸  tï  ¹-0¶-2008¬   givinç 
discourses¬ conductinç Seminaró anä Questionó-Answeró Sessionó aô 
variouó placeó iî anä arounä Berlin® Sré Sharmajé conducteä  morå 
thaî 3° programmeó iî Germany.
Iî  Indiaî Embassy¬ oî ¶-0¶-2008¬ Gurujé delivereä  á  scholarlù 
lecturå  oî  Brahmá Sutrá Bhashyaí oæ  Sré  Shankaracharya.  Thió 
lecturå  waó receiveä verù welì bù thå audiencå anä therå waó  aî 
excellenô interactioî witè thå participants.
Oî ´-0¶-2008¬ Gurujé gavå á lecturå oî ``Sweetnesó oæ Sanskriô iî 
thå  Bhagawaä  Gita'§  iî  thå  Indologù  Departmenô  oæ  Leipziç 
University®  Iô waó welì attendeä anä receiveä bù thå  professoró 
anä thå studentó oæ thå University.
Vidwaî  Sharmajé (Guruji© ió quitå humblå anä simple¬  unassuminç 
Vedantin¬ hió needó arå verù less® Eveî iî Germanù hå  maintaineä 
thå  samå Indiaî Traditionaì stylå aó aô home® Oî thå  wholå  thå 
touò waó quitå successfuì anä wå arå highlù benefiteä tï á  greaô 
extenô  iî hió company® Ouò humblå anä sincerå parnamó  tï  Pujyá 
Sharmaji.
@SIGÎ  ½ Berlin¬ Germanù	Smt® Geethá Munikoté and<R>Dateº  2¸-0¶-
2008	Dr® Vijayendrá Munikoti
Mahamahopadhyaya¬            Rashtrabhooshana<R>Dr®            R® 
Sathyanarayana<R>M.Sc., Ph.D., D.Litt., D.Litt(hon).,<R>F.R.A.S.¬ 
F.A.M.Ò.¬ F.Á.S.É., M.S.Á., I.C.T.M<R>Indirá Gandhé Memoriaì Fellow
`Trayeelakshmi'<R>9tè   Cross¬  4tè  Main¬   Jayanagar<R>Mysore<|¾-
<|>570<|>014®    INDIA<R>Phº   (0821©    2567<|>891<R>Mobº    (0© 
94484<|>88·51
 