@T± ½ Prabodhá Cint<193>ma<207>i
@T² ½ 5° Articleó oî Morals¬ Righteousnesó anä Reality
@T³ ½ Mah<193>mahop<193>dhy<193>ya<R>Vidwaî K® G® Subrayá Sharma¬ 
M.A.,
@T´ ½ Publisher<R>Sré Nithyanandá Prakashana<R>Ashoká Nagar¬  Bengalurõ 
560<|>050
@Tµ ½ 2010
@IMĞ  ½  Prabodhá Cintaamané iî English<R>5°  Articleó  oî  Morals¬ 
Righteousnesó  anä  Reality
@IMĞ ½ Writteî bù `Mahaamahopaadhyaaya§ Vidwan Sré K®  G® 
Subrayá  Sharma¬  M.A.,<R>No®  29¬ 4tè Main¬  5tè  Cross<R>N®  R® 
Colony¬  Bengalore<|¾-<|>560<|>019;Phº  08°-2667<|>3927»  Mobileº 
98862<|>81622
@IMĞ ½ Printeä anä Publisheä bù<R> Sré Nithyanandá Prakashana<R>£ 46¬ 
4tè Cross¬ Ashoë Nagar¬ BSË 1sô Stage<R>Bengalurõ-560<|>050»  Phº 
08°-2242<|>6027
@IMĞ ½ Pagesº	Priceº Rs.
@IMĞ ½ Firsô Editionº Maù 201°» 300° Copies
@IMĞ ½ Alì Rightó reserveä bù thå Author
@IMĞ     ½    Foò    detailó    anä    otheò     Bookó     Pleaså 
Contact:<R>`Mahaamahopaadhyaaya§  Vedá  Brahmá Sré Vidwaî  K®  G® 
Subrayá  Sharma<R>No®  29¬  4tè Main¬ 5tè Cross¬  N®  R®  Colony¬ 
Bengaluru<|¾-<|>560<|>019»          Phº          08°-2667<|>3927¬ 
98862<|>81622<R>emailº kgssharma@gmail.com
Printeä at<R>Sré Nithyanandá Prakashana<R>£ 46¬ 4tè Cross¬  Ashoë 
Nagar<R>BSË 1sô Stage¬ Bengaluru<|>-<|>50<R>Phº 080-2242<|>6027
@È ½ Preface
Vidwaî Ved® Br® Sri® K® G® S® Sharma¬ havinç spenô 1¶ lonç years® 
Aó  á disciplå iî `Gurukula§ systeí witè hió mosô revereä  Gurujé 
Sré  Sré  Satchidanandendrá Saraswathé oæ  Holenarasipuò  (Hassaî 
Dist®  Karnataka©  haó becomå aî exponenô oæ Vedantá  (Thå  Hindõ 
Philosophy)`parexcellence'® Hå haó mastereä thå extremelù  subtlå 
ideaó  iî  thå  workó  oæ  Sré  Shankaracharya'ó  Brahmá  Sutras¬ 
Gaudapada'ó  Mandukyá Karikaó anä aó welì aó  Dashopanishadó  anä 
thå allieä subjects® Hió unparalleä `Gurõ Shishrusha§ yieldeä hií 
thå  uniquå  abilitù  tï  makå  lesó  educateä  anä  panditó   tï 
understanä thå intricacieó oæ Hindõ Philosophù anä Vedanta.
Havinç  beeî  aô  thå  acmå  oæ  intellecô  anä  overlookinç  thå 
confluencå  oæ  thå pathó oæ philosophy¬  Vedantá  anä  Vyavahará 
attracteä  onå anä alì bù hió excellenô oratorù anä broughô  theí Šalì tï thå virtuouó path® `Voø Populi¬ Voø Dei§ (L© Thaô is¬  thå 
Voicå  oæ  peoplå  ió  thå Voicå oæ  GOD®  Thió  broughô  hií  aî 
unthinkablå numbeò oæ awardó `Honoò Virtutió Praemiuí (L© i.å thå 
honoò ió thå rewardó oæ virtues.
Aó  É coulä seå thå Englisè versioî oæ thå 5° articleó  publisheä 
somå timå agï iî á newó dailù `Kannadá Prabha§ aó unique¬  simplå 
anä  intelligiblå  bù  onå anä alì witè thå  efficienô  usagå  oæ 
appropriatå  words® Theså articleó arå wortè reading®  Theså  arå 
thå eyå-openeró foò alì tï overcomå eveî thå simplå situationó iî 
ouò dailù routine.
É  aí  extremelù  happù tï writå theså fe÷ lineó  abouô  mù  mosô 
revereä Gurujé anä hió articleó (iî thå book© aó É haä thoroughlù 
gonå througè theí whilå prooæ reading.
Maù  thå almightù blesó hií anä hió familù witè alì thaô  ió  thå 
besô  iî  thå worlä sï thaô many¬ manù sucè pearló rolì  ouô  hió 
sacreä pen.
Adieî	(Gurupadarenu)<R>Dateº ±-µ-201°	Profº T® Ashwathanarayaná 
Rao<R>08°-2671<|>9762»  98454<|>3875°	 `Aravinda'¬  875¬  14tè 
Cross¬ 19tè Main<R>	Banashankaré 2nä Stage¬ Bangalore-70
