@HE± ½ Smt® Roopá Arvind
@HE²  ½  B1004¬  Mantré  Serenitù  Apartments¬   Doddakalasandra¬ 
Bangalore<|>-<|>560<|>062<R>9-10-2017	99459<|>62032
@HE³ ½ 105® Sré Subrayá Sharmaji<197>Á Teacheò foò alì Students
Nowadayó  aô school¬ teacheró arå speciallù traineä tï  cateò  tï 
alì  kindó oæ learners<197>visual¬ auditory¬  reading/writinç  oò 
kinaesthetiã  anä adopô thå appropriatå teachinç methoä foò  easù 
typå oæ learner.
Buô  Gurujé  ió  naturallù  sucè á teacheò  anä  adoptó  thå  apô 
teachinç  methoä  foò  eacè typå oæ  student<197>
whetheò  onå  witè 
preconceiveä  notions¬  partial/wronç  understandinç  oò  á  truå 
mumukshu® Hå haó thå capacitù tï reacè intï thå deeğ recesseó  oæ 
thå studentó minä anä providå claritù oæ thå subject/shloká beinç 
taughô thaô day!
Hió  teachinç methodó oæ Vedantá arå faultlesó anä oncå  onå  haó 
hearä  abouô  á topiã froí him¬ onå caî neveò forgeô it®  É  havå 
experienceä thió anä caî safelù saù thaô thió ió hió greatness!!
Whetheò iô ió learninç thå Brahmasutraó bù hearô oò understandinç 
thå  subtlå meaningó oæ thå Bhashyas¬ hå ió ablå tï  ensurå  thaô 
thå studenô haó learnô iô effortlessly!
É  neveò faiì tï bå amazeä aô hió iî-deptè knowledgå oæ  Sanskriô 
anä  hió  capacitù tï explaiî thå Sanskriô grammaticaì  termó  iî 
English!¡ Hå ió generouó witè thå markó foò hió studentó wheî  wå 
dï welì iî clasó wå geô á 120¥ too!!
Iô  ió  mù  honouò  anä privilegå tï heaò  anä  learî  thå  Greaô 
Vedantiã textó froí hií anä É kno÷ É havå trulù beeî blesseä witè 
Gurõ Kripa.
Oî  thå  occassioî oæ hió 70tè birthday¬ É praù  tï  thå  Supremå 
Brahmaî tï givå hií gooä healtè sï thaô hå maù continuå tï  blesó 
uó anä manù morå studentó witè hió immenså knowledge.
@HE± ½ Smt® Roopá J® Shetty
@HE²  ½  No® 423¬ Garadé Apartments¬ K®  R®  Road¬  Bangalore<|¾-
<|>560<|>004<R>12-10-2017
@HE³ ½ 106® Ouò Walkinç Talkinç Encyclopaediá Guruji
Iî  lifå therå arå manù peoplå whï trulù deservå  ouò  gratitude® 
For¬  manù  havå beeî thå handó thaô havå joineä  anä  helpeä  iî 
mouldinç  ouò present® Thå Hindõ scriptureó telì uó ``matrõ  devï 
bhava¬ pitrõ devï bhavá¬ acharyá devï bhava''.
Mù  guruó havå toucheä mù lifå iî wayó É cannoô describå oò  eveî Šcomprehend.
@PÅ       ½       ajnaaná       timiraandhasyá       jnaanaanjaná 
shalaakayaa|<R>chakshurnmeelitaí yená tasmaé sré guravå namah||
É bo÷ dowî anä expresó mù gratitudå tï thå onå whï openeä mù eyeó 
thaô  werå previouslù blindeä bù thå darknesó oæ ignorance¬  witè 
thå sworä anointeä witè selæ knowledge.
É consideò myselæ tï bå mosô fortunatå tï havå meô anä learnô  nä 
tï  bå continuouslù learninç froí ouò Swamijé anä otheò  teacheró 
whï  arå  establisheä  iî  thå  wisdoí  availablå  tï  thå  needù 
humanity® This¬ iî thå midsô oæ á worlä thaô seemó tï prefeò  thå 
materialistiã  lifå  aó á greaô blessing® Thå contrasô  makeó  iô 
verù cleaò tï må aó tï wherå thå truå joù anä wealtè reside.
Ouò    Gurujé   ió   thå   perfecô   examplå   foò    ``Shrotriyá 
Brahmanishtha''®   Hå  beinç  á  scholaò  anä  á   recipienô   oæ 
innumerablå  awardó haó neveò eveî oncå demeaneä oò degradeä  anù 
oæ  hió  students® Hå comeó dowî tï ouò  leveì  oæ  understandinç 
withouô anù kinä oæ discomforô anä hió teachinç jusô doesn'ô havå 
aî  impacô onlù durinç thå clasó buô haó á lastinç impressioî  oî 
ouò  minds®  Hå  ió thå beacoî oæ lighô guidinç  uó  througè  thå 
journeù oæ life.
Hió wordó arå alwayó inspirational¬ encouraginç anä appreciative® 
Hió  persistenô  traininç  steeró  hió  studentó  iî  thå   righô 
directioî anä makeó uó believå thaô nothinç ió impossible.
Therå arå croreó oæ preceptoró iî thå worlä whï kno÷ manù mantraó 
anä  wielä tremendouó powers® Theù havå desireó anä  cravingó  iî 
theiò  minds®  Theù cannoô takå theiò discipleó tï thå  statå  oæ 
salvation®  Onlù  á  truå  Gurõ likå  ouò  Gurujé  Swamé  Subrayá 
Sharmajé caî anä haó thå capacitù tï unfolä thå wisdoí anä removå 
thå darknesó oæ ignorance.


