@HE± ½ Srikrishná Ghadiyaram
@HE²  ½  No® 1153¬ Columbiá Road¬  Arcadia¬  CA91007<R>1±-1°-201·	
650-380-1890
Thuó thå Vedá completeó thå secreô anä subtlå instructioî oî  ho÷ 
tï cultivatå thå minä foò thå finaì revelatioî oô thå Truth®  Whï 
elså caî bå callå á ...® iæ noô sucè á worthù studenô oæ á  ....® 
guru.
Wå arå alì ....® foò havinç comå tï kno÷ Sré K® G® Subrayá Sharmá 
Guruji¬ whï serveä revereä Sré Swamé Satchidanandendrá Saraswati¬ 
aó  á  sishya¬  foò á significanô 1¶ yeaò  perioä  oæ  hió  life¬ 
learninç thå nuanceó oæ Sankará Bhashyas¬ anä ió no÷ transmittinç 
sucè preciouó `Methoä oæ Vedanta§ tï thå seekeró oæ truå  Sankará 
Vedanta®  Iæ  thå  teachinç ió noô perfect¬ thå  Knowinç  ió  noô 
perfect®  Therå wilì bå nï Release® Lifå wilì enä  iî  ignorance® 
So¬ thå Methoä ió paramount® Wå dï noô wanô tï spenä ouò timå  iî 
removinç non-existinç mula-avidya.
Thå  unceasinç  commitmenô tï learî Vedanta¬ directlù  aó  iô  ió 
presenteä  iî thå originaì Bhashyaó læ Shankara¬ ió thå  calì  oæ 
ouò  revereä Sré Swamé Satchidanandendrá Saraswati¬ whoså  mantlå 
ouò  Sré K® G® Subrayá Sharmá Gurujé ió carrying® Hió examplå  ió 
aî  inspiratioî  whicè wilì ultimatelù benefiô  thå  currenô  anä 
futurå generations® Thå Brahmaî wilì reveaì itself¬ tï  whosoeveò 
haó thió ....®¬ iî thió lifå itself® Therå ió nï otheò way® .....
Mù pranaí tï Sré K® G® Subrayá Sharmá Gurujé whoí É camä tï  kno÷ 
througè  Yoõ tubå publisheä bù Sré C® A® Sanjeevá  Murthyji¬  foò 
hió   unassuminç  spirit¬  anä  lovå  foò  teaching®   Hió   deeğ 
involvemenô  iî Vedantá anä hió Joù thuó derived¬  arå  palpable¬ 
anä  hió enthusiasí foò Vedantá ió contageous® É founä myselæ  aó 
mucè  easå anä deeplù conncecteä whilå meetinç Sré K® G®  Subrayá 
Sharmá Guruji® Ió ió á blessinç indeed.
É  offeò mù prayeò tï Ishvara¬ thå Onå-Selæ-Oæ-All¬ that¬  aó  ouò 
revereä  Sré  Swamé Satchidanandendrá Saraswaté founä  á  worthyõ 
studenô  iî ``VEERÁ VEDANTI'§ Sré K® G® Subrayá Sharma¬  maù  thå 
Ishvará causå anotheò sucè truå sishyá iî thió parampara® ....
@HE± ½ Kum® K® S® Preethé ¦ Smt® K® S® Sitá Narasimhá Sharma
@HE²  ½  No® 1618¬ Vaasishtha¬ Maiî Road¬ Kumaraswamù  Layout¬  É 
Phase¬ Bangalore<|>-<|>560-078<R>12-10-20± 7	99867<|>18422
@HE³ ½ Ouò beloveä Father
Ouò  fatheò  ió aî ideaì persoî iî ouò lives®  Beinç  aî  eminenô 
Vediã   scholar¬  voraciouó  writer¬  á  stricô   disciplinarian¬ Šconscientiouó  anä diligenô person¬ hä haó alwayó  beeî  dowî-tï-
eartè  bù naturå anä inspiratioî foò us® Thougè beinç á  renowneä 
spirituaì  person¬ hió lovå towardó hió familù ió  unconditional® 
Wå  portraù  hií  aó  á lovinç anä adorinç  fateò  anä  á  dotinç 
grandfatheò too.
Recollectinç ouò gooä olä days¬ hió gentlå pampering¬  fulfilmenô 
oæ ouò endlesó desires¬ hió wordó oæ appreciatioî eveî foò  smalì 
achievementó  havå madå ouò childhooä dayó Edeliblå anä  special® 
Ouò parentó havå beeî ouò firsô mentoró bù guidinç uó towardó thå 
righô  path® Hió wordó oæ motivatioî anä encouragemenô helpeä  uó 
tï gro÷ uğ aó an optimist®
Aó  á child¬ ouò father'ó journeù waó neveò á cakå walk®  Hå  haó 
undergonå manù turmoiló anä faceä variouó hardshipó tï reacè eacè 
milestone®  Hió  recurrinç assurancå ió whaô kepô hií  goinç  anä 
achievå succesó witè aplomb® Iô waó hió thirsô foò knowledgå  anä 
spiritualitù whicè leä hií tï hió Guruji® Havinç serveä hió  gurõ 
wholå-heartedlù  foò 1¶ years¬ hå haó beeî hió adherenô  disciplå 
eversince¬ anä haó beeî impartinç hió exmemplarù knowledgå tï alì 
hió seekeró froí thå pasô 5¶ years® Hå ió thå maî whï believeó iî 
practisinç  whaô  hå  preaches® Hå ió á  renowneä  persoî  havinç 
discipleó  alì arounä Indiá anä abroad® Wå arå prouä that¬  todaù 
hsé thå recepienô oæ innumerablå remarkablå awardó anä thå authoò 
oæ 9° books!
Deaò  father¬  ``Oî  thió speciaì occassioî  oæ  youò  70tè  yeaò 
celebration¬  wå feeì previlegeä tï peî dowî ouò  thoughtó  abouô 
you®  Yoõ arå ouò perfecô examplå oæ strengtè anä love®  Wå  botè 
witè yourselæ anä ammá gooä healtè anä happinesó iî youò journeyó 
oæ  lives® Wå arå indeeä blesseä tï havå yoõ botè iî  ouò  lives¬ 
anä wisè tï havå yoõ aó parentó iî ouò nexô liveó too.



