@HE± ½ Sré S® N® Mohan
@HE² ½ No. Á-205¬  Brigadå Omega¬ Opp® Thurahallé Forest¬  8°  ft®  Road¬ 
Banashankaré 6tè Stage¬ Bangalore<|¾-<|>560<|>062<R>2-10-2017	87623<|>87554
@HÅ3 ½ Sharmajé¬ Aó É know
Arounä  beginninç oæ Apriì 2013¬ É haä thå privilegå  oæ  meetinç 
Gurujé  anä  attendinç  firsô Vedantá clasó  aô  Vedantá  Nilaya¬ 
Sakammá  Gardens¬ Bangalore® Sincå then¬ myselæ anä mù wifå  Smt® 
S®  N®  Nagaprabhá arå attendinç Guruji'ó Vedantá  classes®  Eveî 
thougè  wå  arå hió studentó foò thå pasô ´  years¬  Gurujé  madå 
immenså  contributionó iî ouò dailù life® Therå arå manù whï  arå 
Guruji'ó  shishyaó  foò morå thaî 3° years® Gurujé ió  verù  mucè 
dedicateä  anä  applieä himselæ foò  spreadinç  Shankará  Vedantá 
througè  hió  teachingó  anä writingó oæ abouô  ninetù  bookó  oî 
variouó  topics®  Hió  writingó  arå  simplå  anä  verù  easù  tï 
understand.
Humaî  birth'ó  primarù  objectivå ió tï  kno÷  abouô  Brahmá  bù 
studyinç  Vedantá  Bhashyá undeò thå guidancå oæ  Gurujé  aó  thå 
materialistiã  aspectó  oæ lifå thougè appearó  interesting¬  arå 
temporarù iî nature® Gurujé ió explaininç thió poinô everydaù  iî 
Shankará  Bhashyá  classeó givinç livå illustrations®  Everù  daù 
startó livelù wheî wå attenä hió Vedantá classeó anä lifå appearó 
meaningful®  Besides¬  Gurujé ió simple¬ dowî tï  eartè  anä  hió 
blessingó anä adviceó arå makinç ouò liveó interesting® Wå cannoô 
repaù  hií iî anù waù foò hió contributionó iî ouò life®  É  onlù 
praù  Almightù  foò hió lonç healthù life¬ sï thaô hå  caî  carrù 
forwarä hió contributionó tï Vedantá foò thå benefiô oæ mankind.







