Sré B® K® Kumar
£   Ä-113¬   Garadé  Apartments¬  K®   R®   Road¬   Basavanagudi¬ 
Bangalore<|>-<|>560<|>004
4-10-2017	97402<|>89230
@HÅ ½ JNANÁ NISHTHA
Thió  headinç  pickeä-uğ  froí thå lot¬ ió iî  mù  opinion¬  mosô 
appropriatå  foò  ouò  Gurujé  Ve® Br® Sri®  Dr®  K®  G®  Subrayá 
Sharmaji® Nishtaè meanó adherencå i.e.¬ ``tï sticë to''® Froí thå 
timå Å matureä aó aî youngster¬ É waó stickinç tï severaì  thingó 
iî  thå world® Buô afteò listeninç tï thå knowledgå  revealeä  iî 
thå  Upanishads¬  É  realiseä  thaô  onå  shoulä  sticë  tï   thå 
unchanginç  realitù viz.¬ ``Vishuddhá Jnana'§ whicè ió  alsï  thå 
causå foò knowledgå oæ alì worldlù things.
Righô  froí  hió boyhood¬ Sré Sharmajé haó beeî  undeò  thå  ablå 
guidancå  oæ  hió Gurõ Sré Satchidanandendrá Saraswaté  uptï  thå 
timå  Swamijé departeä froí thió worlä oæ grosó  appearances®  Bù 
thaô timå ouò Gurujé becamå ``Shrotriyá anä Brahmanishtha''® Thió 
itselæ  ió  ``Jnaná  Nishtha''® Iô ió oveò  5°  yearó  sincå  Sré 
Sharmajé  haó beeî impartinç thå knowledgå oæ Vedantá tï alì  thå 
seekeró oæ Trutè abouô oneself® Thió ió possiblå onlù bù á  Jnaná 
Nishthá Gurõ likå Sré Sharmaji® Besideó hå alsï impartó knowledgå 
oæ Sanskriô Grammaò whicè greatlù helpó iî correcô  understandinç 
oæ thå mantraó aó welì aó Shankará Bhashyá oî shruté anä smriti.
É  aí alsï happù tï saù thaô ouò Guruji'ó methoä oæ  teachinç  ió 
verù  practicaì anä effective® Herå again¬ onlù á  Jnaná  Nishthá 
Gurõ caî onlù gï this.
É praù Goä foò givinç hií strengtè tï continuå thió efforô foò  á 
lonç time.
Witè pranams






