@HE± ½ Smt® Kavitá R
@HE² ½ No.332¬ Architá III¬ GL¬ 18tè Cross¬ Ideaì Homeó Township¬ 
R® R® Nagar¬ Bangalore<|>-<|>560<|>098<R>
11-10-2017	99860<|>35022
@HE3 ½ 98® Gurõ Divine
É havå learnô tï counô mù blessings¬ neveò ponderinç oî thå  pasô 
anä tï seå thå purå futurå witè thå knowledgå froí youò  classes® 
Yoõ  taughô  må  tï bå confident¬ É coulä dï iô iæ  É  trieä  anä 
taughô  må  tï havå couragå tï takå everythinç iî  stride®  Everù 
meetinç  witè  yoõ haó beeî oæ thaô divine¬ neveò  navå  yoõ  biä 
adieõ withouô givinç må á treasurå oò two¬ whoså valuå É  realiså 
iî á daù oò two¬ everù pearì oæ knowledgå yoõ droğ iî mù lağ ió á 
diamonä  whicè  shineó  brighô witè everù increaså  oæ  mù  inneò 
light.
Likå floweò froí thå seedlinç yoõ helğ eacè tï grow¬ nurturinç må 
anä  alì  whï  crosó  youò  patè  witè  knowledgå  divine®  Everù 
colourfuì  descriptioî oæ somå tastù biteó straighô froí  kitcheî 
whicè  teacheó subtlå lessonó oæ `Whï aí I'® Youò dedicatioî  anä 
sinceritù  humbleó må tï core¬ therå ió mountainouó knowledgå  iî 
youò treasurå trovå tï learî iî thió lifå time.
Mù eyeó sï fulì oæ queries¬ answeró yoõ explaiî likå storieó tolä 
likå  taleó  abouô  trutè É caî attain® Sharinç  anä  carinç  yoõ 
demonstratå  alì  alonç whilå yoõ pouò knowledgå rarå  froí  holù 
bookó­-Upanishads¬  Bhagavadgita¬ Brahmasutrá anä simplå  lessonó 
iî  life¬  yoõ sharå witè lovå tï measurå whicè aî  instrumenô  É 
faiì tï find.
Simplicitù  anä humilitù yoõ adorî aó á danglinç  necklacå  whicè 
sparklå everù steğ yoõ take¬ iî itó reflecteä lighô yoõ blesó alì 
everù  timå  wå  meet®  Mù mother¬  father¬  husbanä  anä  child¬ 
everyonå yoõ blesseä witè youò lovå divine® Nothinç caî É finä tï 
measurå  thå  abundancå  yoõ showeò oî onå anä all®  É  counô  mù 
blessingó  foò  yoõ  crosseä mù patè tï sho÷  må  lighô  É  carrù 
within® É praù tï Lorä foò á lonç life¬ tï neveò loså yoõ iî thió 
worlä oæ illusioî guidinç må froí darknesó tï light.
@HE± ½ Smt® Shaliné Prasad
@HEÀ    ½    No®   30¬   `Anandam'¬   Ideaì    Homeó    Township¬ 
Rajarajeswarinagar¬        Bangalore<|¾-<|>560<|>098<R>1±-1°-201·	
97400<|>73107
@HE²  ½  99® Aî exemplarù Livinç Vedantiî  oæ  ouò  times<197>Sré 
SharmajiŠIî  ouò  Vedantá  classes¬ wå listeî tï anä  ofteî  uså  vedantiã 
jargonó  sucè  aó  asangatva¬  detachment¬  unconditionaì   love¬ 
unconditionaì   happiness¬  equanimitù  oæ  mind¬  worë  iî   thå 
transactionaì  worlä mosô efficiently¬ yeô remaiî rooteä  iî  thå 
Absolutå  Realitù  etc.¬ etc® Wå kno÷ thaô theså arå  alì  easieò 
saiä  thaî  done® Wå alsï understanä thaô iô takeó  manù  janma'ó 
sukrutaphalá tï bå eveî jusô exposeä tï thå shastras¬  especiallù 
froí á Guru.
iî mù beloveä Gurõ Sharmaji¬ É havå seeî alì thoså jargonó tï  bå 
á  parô  oæ  him®  Hå ió  sï  naturallù  loving¬  unconditionallù 
accepting¬ eveò jumpinç iî joy¬ á lovinç buô firí Guru¬ á beloveä 
husband¬  á dotinç fatheò anä no÷ á verù lovinç grandfatheò  too¬ 
yeô  completelù  detached¬  alwayó  maintaininç  equipoise¬  eveò 
abidinç iî thaô statå oæ Blisó thaô wå arå alì hungrù for¡ Hå haó 
taughô uó noô jusô whaô thå shastraó reveal¬ buô alsï ho÷ wå  caî 
actuallù bå alì oæ that¡ Hå haó demonstrateä iî hió dailù  livinç 
ho÷  beinç á grihastha¬ enjoyinç alì privilegeó oæ  á  grihastha¬ 
alwayó  joyous¬  irrespectivå oæ thå happeninç  around¬  onå  caî 
stilì  livå Vedantá anä abidå iî thå Absolutå Reality¬  ouò  verù 
nature®  Krishná  tolä  uó  througè  thå  Bhagavadgitá  thaô  thå 
battlefielä  wå arå puô into¬ ouò kshetra¬ that'ó wherå  wå  musô 
strive¬ neveò foò á momenô forgettinç whï É reallù am® Thió  alsï 
ió sï powerfullù demonstrateä iî ouò beloveä Guruji'ó lifå thaô É 
havå seen.
É havå beeî tolä thaô whaô É dï witè whaô ió giveî bù Bhagavaî tï 
må ió mù gifô gï Him® Beloveä Sharmajé waó indeeä blesseä bù  thå 
besô  Gurõ anä thå reminiscenceó oæ Subrayá Sharmá  Gurujé  abouô 
hió  Gurõ ió imprinteä iî mù mind® Iô ió indeeä amazinç ho÷  thaô 
knowledgå  poureä bù Sré Sré Satchidanandendrá Saraswaté  Swamijé 
ontï hió devoteä disciplå ió no÷ beinç poureä dowî foò alì oæ  uó 
tï  partakå  of® Froí herå on¬ whaô É dï witè whaô  hå  giveó  må 
woulä bå mù gifô tï him.
Mù  motheò-iî-la÷ anä É havå haä thå gooä fortunå oæ havinç  himó 
anä hió familù oveò tï ouò houså foò lunch® Wå diä noô feeì  likå 
wå haä guests¬ buô iô waó likå onå biç happù familù enjoyinç  thå 
presencå  oæ  kids¬ enjoyinç á gooä meaì anä  chitchattinç  abouô 
variouó aspectó oæ life® Thå lovå anä affectioî hå showeró oî  uó 
makeó uó feeì sï closå tï him¬ iô ió á blessinç indeed.
Mù humblå pranamó aô hió feeô anä É offeò mù heartfelô  gratitudå 
tï hií anä tï Bhagavaî foò bringinç må tï him® Oí taô sat

