@HE± ½ Sri P® R® Shivashankar¬ B.E.¬ FIE.,
@HE² ½ Indiaî  Railwaù  Servicå oæ Engineers¬  (Rtd.©  Generaì  Manager¬ 
IRCOÎ Internationaì Ltd.¬ No.  104¬  Kumaò  Paradise¬  B®  P®  Wadiá   Road¬   Basavanagudi¬ 
Bangalore¼|>-<|>560<|>004<R>8-10-2017	080-2661<|>0026¬ 97400<|>00755
@HE³ ½ ``Reaì Guru'§ Sré Sharmaji
É camå acrosó á ``Reaì Guru''
Ouò  beloveä Guru¬ Mahamahopaadhyaayá Dr® K® G®  Subrayá  Sharma¬ 
haä  á  mosô immitablå masterlù Gurõ  iî  Sré  Satchitanandaendrá 
Saraswaté Swamijé froí hió younç agå oæ 1° yearó foò á perioä  1¶ 
years¬  whoí hå serveä witè utmosô devotion® Swamijé traineä  ouò 
Gurujé witè everù biô oæ whaô Shankará Advaitá Vedantá standó foò 
aó  alsï Shruti¬ Shadangas¬ Puranaó includinç thå workó oæ  greaô 
Sanskriô writeró likå Kalidasá etc® Iî shorô ouò Gurujé haó  beeî 
chiselleä ouô bù Swamijé aî outstandinç teacheò oæ Vedanta.
É  kno÷  noô  á biô oæ Sanskriô noò haä eveî á  littlå  smelì  oæ 
Advaitá  Philosophù  entirelù aî ignoranô novicå iî  thå  subjecô 
witè ouò additionaì disqualificatioî oæ 8´ yearó oæ age® Thaô ouò 
Gurujé haó madå ouô oæ á Duä iî thå subject¬ aô thió agå intï  aî 
ardenô studenô cravinç foò thå clasó anä sï mucè enjoù iô whtá mù 
onlù  Prayeò tï Goä haó beeî tï keeğ må fiô tilì thå lasô daù  oæ 
mù  lifå sï thaô É maù noô misó á singlå daù oæ  Guruji'ó  class¬ 
speakó tonó oæ thå abilitù oæ ouò Guruji.
Hå  ió simplù aî oceaî oæ knowledgå iî Vedanta® Hå  haó  devouteä 
hió  entirå lifå foò preachinç Shankará Advaitá Vedantá foò  oveò 
5°  years®  Hå talks¬ smells¬ hears¬ reads¬ writeó  anä  breatheó 
Vedantá anä eveî morå practiceó it® É wondeò whaô tï calì hió  aî 
earnesô student/highesô Gurõ oò á Savant/Sarwabhowmá oæ Vedanta.
Leô  uó alì jointlù praù Almighty¬ aó hió devouô  studentó  ``Maù 
hió  tribå increaså anä Hå anä hió  familù bå showereä  witè  thå 
strengtè  needeä  tï  enablå hií tï keeğ  servinç  thå  causå  oæ 
Vedantá  iî thå servicå oæ humanitù aô largå foò yearó anä  yearó 
tï come.
Oí Shanté Shanté Shanti


