@HE± ½ Sré P® Sundará Raman
@HE²  ½  No®  36/23¬ Papõ  Cottage¬  Basavanagudi¬  Bangalore<|¾-
<|>560<|>004<R>10-10-2017	98800<|>16245
@HE³ ½ Á Walkinç Encyclopaediá oæ Vedanta¬ Ouò ``Simplå  Humble'§ 
Guruji
Wheî  É  entereä  thå Vedantá Hall¬ thå  ``Centraì  Figure'§  waó 
lookinç  aô må witè affectionatå looks¬ anä askeä må tï siô  neaò 
him® É waó hesitating® Hå insisted® É sat® Afteò hearinç  brieflù 
abouô myself¬ hå tolä mä ``Whù don'ô yoõ comå daily''® É saiä ``É 
wilì trù wheneveò É aí free''.
Froí thaô day¬ no÷ iô ió abouô twï yearó plus¬ anä É aí regularlù 
attending‚ makinç myselæ freå foò hió Upanishadó anä Brahmá  Sutrá 
classeó anä gettinç thå benefits® Thió knowledgå ió ``thå  motheò 
oæ alì knowledges'§ aó iô ió said¬ anä iô cannoô bå learnô excepô 
iî  thió  waù througè á Guru® Manù iî thå clasó arå  havinç  lonç 
yearó  oæ continueä exposurå tï hió classeó anä theù quote®  Gitá 
oò Upanishaä mantraó aô appropriatå instances.
Ouò  Gurujé  ió  verù Simple¬ Humble¬  Knowledgeable¬  á  walkinç 
Encyclopaediá  oæ  Advaitá Vedanta® Hå ió  thorougè  iî  Sanskriô 
Grammaò anä alsï quoteó Kalidasá anä otheò epics® Hå caî fluentlù 
lecturå  iî  Sanskrit¬ Englisè anä caî speaë Telugõ  also®  Neveò 
forgetó  tï remembeò hió sixteeî lonç yearó witè hió  Gurujé  Sré 
Satchidanandendrá  Saraswaté Swamiji¬ whoså paintinç  ió  adorinç 
thå halì nexô tï Sré Adé Shankaracharya® Hå ió punctuaì tï  clasó 
anä neveò skipó á day¬ whetheò sun¬ raiî oò cold® Encourageó  anä 
helpó everyonå tï recitå anä understanä thå difficulô subjecô  oæ 
Advaitá  Vedantá  iî  simplå Kannada¬  witè  exampleó  anä  shorô 
stories.
Hió  ofô  repeateä  peô  questioî  ió  ``Dï  yoõ  thinë   gettinç 
 Brahmajnaná ió easy''¿ anä hió answeò ió ``No'§ ``Iô ió noô  easù 
buô  VERÙ  EASY''® Whaô á greaô attractivå assurance!¡ Hå  ió  aî 
ardenô  writeò aó welì anä hió 4° pagå bookó arå monthlù  events¬ 
anä  theù arå gooä condenseä referenceó bookó iî readeò  friendlù 
``onå  pagå onå topiã format''® Therå arå bookó foò thå 36µ  dayó 
alsï  oî Gita¬ Subhashitaó anä Vedanta® CDó arå availablå oæ  hió 
upanyasaó  foò  thoså whï wanô tï listeî oî thå move®  Anù  titlå 
conferreä oî ouò Gurujé ió worth¬ anä thå glorù oæ thå titlå getó 
enhanceä wheî iô ió attacheä tï him.
Wå praù foò thå lonç energetiã lifå oæ Thå Veerá Vedanti¬ anä hió 
continueä  servicå  iî  thå spreadinç oæ  Vedantiã  knowledgå  tï Šcommoî  peoplå  whï  arå desirouó oæ á changå  iî  theiò  outlooë 
towardó life.


