@He± ½ Sré K® S® Maheshá Babu¬ Secretary¬ Sré Shankará Jayanté Mandali
@he²  ½  45¬  16tè Cross¬  3rä  Block¬  Jayanagar¬  Bangalore<|¾-
<|>560<|>011<R>7-10-2017	99001<|>98673
@he³ ½ Dr® Sharmaji¬ Spirituaì Master
Iî  thió  busù world¬ verù fe÷ peoplå woulä likå tï  realiså  thå 
purposå  oæ  philosophù  anä spirituaì  wisdoí  iî  thå  shortesô 
possiblå time.
Thå  sacreä  trutè  containeä iî thå  Vedaó  anä  Upanishadó  arå 
explaineä  iî simplå formó througè lectures¬ bookó anä CD's®  Thå 
maiî  aií  oæ theså lectures¬ bookó anä CD'ó ió  tï  helğ  peoplå 
clearlù  understanä  iî deptè anä tï havå  aî  experiencå  calleä 
<MI>Anubhavá Vedanta<D>.
Ouò Vidwaî Dr® K® G® Subrayá Sharmaji¬ whï ió á spirituaì  masteò 
haó   understooä  thå  societù  anä  iî  thió  directioî  hå   ió 
responsiblå iî bringinç ouô smalì bookó anä CD'ó tï enablå peoplå 
tï  understanä  thå compleø treasurå houså oæ knowledgå  anä  thå 
eternaì  valueó  oæ  life® Ouò  Gurujé  continuouslù  strikeä  iî 
bringinç ouô thå teachingó oæ Sré Shankará Bhagavatpadá iî  brieæ 
anä helğ iî thå promotioî oæ Dharma.
Dr®  K® G® Subrayá Sharmajé ió á greaô Spirituaì teacheò  whï  ió 
takinç  thå societù forwarä witè hió dynamiã personalitù  inspitå 
oæ variouó difficulties.
É woulä likå tï expresó mù deeğ regardó anä respectó tï Gurujé iî 
á verù humblå way.




