@h±å ½ Mrs® Santhá Natarajan
@h2å ½ Dateº 7-10-2017	9±<|>80<|>25530932
@h3å ½ Á walkinç Encyclopaedia
Eveî  thougè  É  aí noô welì verseä iî Sanskrit¬  É  aí  ablå  tï 
understanä  thå  Upanishaä mantras¬ Brahmá  Sutraó  anä  Shankará 
Bhashyaí onlù becauså oæ Guruji'ó abilitù tï communicatå  compleø 
topicó iî á simplifieä anä easilù comprehendablå manner® Guruji'ó 
knowledgå  anä greatnesó ió quitå difficulô tï summarizå  aó  hió 
knowledgå  ió  faò anä widå aó welì  aó  deep<160>coverinç  Veda¬ 
Vedanta¬   Puranas¬  Itihasas¬  Kalidasá  Kavyas¬   Subhashitani¬ 
Amarakoshas¬  Vyakaraná  etc®  etc.¬  anä thå  lisô  wilì  gï  oî 
endless® Alì theså subjectó arå verilù aô ouò Sré Guruji'ó fingeò 
tips¬  iî  fact¬ wå caî calì hií á walkinç encyclopaediá  anä  aî 
eveò-oî computeò witè enormouó storagå capacity.
Wå caî withouô doubô proclaií thaô therå ió nï persoî todaù otheò 
thaî  ouò  Gurujé  whï  teacheó  Shankará  Bhashyaí  witè   padá-
padaarthá-anvayá  kramá tï thå generaì public® Anybodù  attendinç 
hió classeó wilì gï bacë fulì oæ energy¬ enthusiasí anä  abundanô 
positivitù   thaô  radiateó  froí  him®  Hå  woulä   continuouslù 
encouragå eacè anä everù studenô bù callinç theí ``Gnani'§  whicè 
encourageó alì oæ uó tï pursuå theså studieó witè morå vigour.
Manù oæ uó kno÷ thaô ouò Sré Gurujé haó haä thå greaô fortunå  oæ 
beinç  aî  Antevasé  disciplå  oæ  thå  highlù  revereä  Sré  Sré 
Satchidanandendrá Saraswathé Swamiji¬ Startinç hió gurukulá  witè 
Swamijé aô thå tendeò agå oæ 8¬ hå waó traineä systematicallù anä 
elaboratelù  aó  welì  aó verù strictlù bù  thå  Swamijé  oî  alì 
aspectó  oæ  ouò Sanathaná Dharmá aó welì seculaò  education®  Iî 
addition¬  Swamijé  haó  madå  ouò Gurujé  proficienô  iî  alì  ³ 
languages.
Mù humblå pranamó tï ouò revereä Guruji® Jayá Jayá Shankara¬ Hará 
Hará Shankara
