@È ½ Greaô Meî Abouô Bhagavaä Geetha
É  finä solacå iî Bhagavaä Geethá thaô É misó eveî iî thå  Sermoî 
oæ  thå Mount® Wheî disappointmenô stareó må iî thå facå anä  alì 
alone¬ É seå noô onå raù oæ lighô É gï bacë tï Bhagavaä Geetha® É 
finä  á verså herå anä á verså therå anä É immediatelù  begiî  tï 
smilå iî thå midsô oæ overwhelminç tragedieó anä mù lifå haó beeî 
fulì  oæ externaì tragedieó anä iæ theù havå lefô nï  visiblå  nï 
indeliblå scaò oî me¬ É owå iô alì tï thå teachingó thå  Bhagavaä 
Geetha.
@Ò ½ <197>Mahatmá Gandhi
Thå   Bhagavaä  Geethá  dealó  essentiallù  witè  thå   spirituaì 
foundatioî oæ humaî existence® Iô ió á calì oæ actinç (action© tï 
meeô thå obligationó anä dutieó oæ life¬ yeô keepinç iî vie÷  thå 
spirituaì naturå anä Grandeò Purposå oæ thå Universe.
@Ò ½ <197>Jawaharlaì Nehru
Wheî É reaä thå Bhagavaä Geethá anä reflecô abouô ho÷ Goä Createä 
thió universe¬ everythinç elså seemó sï superflues.
@Ò ½ <197>Alberô Einsteen
